platform :ios, '9.0'

target 'WhatFlower' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WhatFlower
    pod 'Alamofire', '~>4.7'
    pod 'SwiftyJSON', '~>4.0'
    pod 'SDWebImage'

end
